club_log:
    resource: "@ClubLogBundle/Controller/"
    type:     annotation
    prefix:   /

ClubUserBundle:
    resource: "@ClubUserBundle/Controller/"
    type: annotation

login_check:
    pattern:   /login_check
